apiVersion: v1
kind: Service
metadata:
  name: githubactionsplayground
spec:
  type: NodePort
  selector:
    app: githubactionsplayground
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactionsplayground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubactionsplayground
  template:
    metadata:
      labels:
        app: githubactionsplayground
        version: v0.1
    spec:
      containers:
      - name: githubactionsplayground
        image: REGISTRY_URL/githubactionsplayground:IMAGE_LABEL
        ports:
        - containerPort: 80
