name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Kubectl setup
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
      id: setcontext

    - name: Build, push, start
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_URL }}/githubactionsplayground:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_URL }}/githubactionsplayground:${{ github.sha }}
        sed -i 's/REGISTRY_URL/${{ secrets.REGISTRY_URL }}/g' k8s.yaml
        sed -i 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
        kubectl apply -f k8s.yaml
