name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_URL }}/githubactionsplayground:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_URL }}/githubactionsplayground:${{ github.sha }}
